FROM {{ARCH.images.base}}

ARG VENDOR_APP_PATH=fork

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY $VENDOR_APP_PATH/package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY $VENDOR_APP_PATH/ .

EXPOSE 3000
CMD [ "node", "server.js" ]

