on:
  push:
    paths-ignore:
      - '.github/**'
      - 'vendors/shooter/**'

env:
  REPO: ${{ github.event.repository.name }}
  DEBUG_MODE: ${{ contains(github.event.head_commit.message, 'ci debug') }}

jobs:
  my_job:
    runs-on: ubuntu-latest
    container:
      image: lasery/ride
      options: >-
        -v "${{ github.workspace }}":"/home/ride/projects/${{ github.event.repository.name }}"
        -e HOST_NAME=${{ github.event.repository.name }}
        -e HOST_DOCKER_ID=121
        -e HOST_USER_NAME=root
        -e HOST_USER_ID=0
        -e HOST_USER_GID=0
        --privileged

    steps:
      -
        name: Checkout repository and submodules
        uses: actions/checkout@v2
      -
        name: Cache home directory
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: /home/ride/.kr
          key: cache-home
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: "Debug:Cache tmp directory"
        if: env.DEBUG_MODE == 'true'
        id: cache-tmp
        uses: actions/cache@v2
        with:
          path: .tmp
          key: cache-tmp
      -
        name: "Debug: let ride own repo"
        if: env.DEBUG_MODE == 'true'
        run: chown -R ride:ride $GITHUB_WORKSPACE
      -
        name: "Debug: symlink kr"
        if: env.DEBUG_MODE == 'true'
        run: ln -s $GITHUB_WORKSPACE/.tmp/.kr /home/ride/
      -
        name: "Debug: run sshme"
        if: env.DEBUG_MODE == 'true'
        working-directory: /home/ride/projects/${{ env.REPO }}
        run: timeout $(expr 5 \* 60 \* 60) /docker-entrypoint.sh ride sshme ${{ env.REPO }} || true
      -
        name: Build with mbuild
        run: python3 /home/ride/mbuild/utils/build.py docker
      -
        name: Push with mbuild
        run: python3 /home/ride/mbuild/utils/build.py push --only
      -
        name: Deply with mbuild
        run: python3 /home/ride/mbuild/utils/build.py deploy --only
