on:
  push:
    paths:
      - 'vendors/shooter/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: hello-cloud-run
  REGION: asia-east2

jobs:
  deploy_shooter:
    if: ${{ false }}  # disable for now
    defaults:
      run:
        working-directory: vendors/shooter
    runs-on: ubuntu-latest
    container:
      image: lasery/ride
      options: >-
        -v "/home/runner/work/templates/templates":"/home/ride/projects/templates"
        -e HOST_USER_NAME=root
        -e HOST_USER_ID=0
        -e HOST_USER_GID=0
        --privileged

    steps:
      -
        name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
            submodules: recursive
      -
        name: Cache home directory
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: /home/ride/.kr
          key: cache-home
      -  # https://github.com/docker/setup-qemu-action#usage
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -  # https://github.com/marketplace/actions/docker-setup-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -  # https://github.com/docker/login-action#docker-hub
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Debug with sshme
        if: "contains(github.event.head_commit.message, 'ci debug')"
        run: cd /home/ride/projects/templates && /docker-entrypoint.sh ride sshme || true
      -
        name: Build with mbuild
        run: python3 /home/ride/mbuild/utils/build.py docker
      -
        name: Push with mbuild
        run: python3 /home/ride/mbuild/utils/build.py push --only
      -
        name: Deply with mbuild
        run: python3 /home/ride/mbuild/utils/build.py deploy --only
      -
        name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true  # Set to true to authenticate the Cloud Run action
      -
        name: Authorize Docker push
        run: gcloud auth configure-docker
      -
        name: Build and Push Container
        run: |-
          docker tag templates:amd64 gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
      -
        name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID  }}/${{ env.SERVICE  }}:${{  github.sha  }}
          credentials: ${{ secrets.GCP_SA_KEY }}
      -
        name: Use Output
        run: curl "${{ steps.deploy.outputs.url }}"
